// <auto-generated />
using ConRes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConRes.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526203657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ConRes.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Satoru Gojo",
                            Password = "gojopass",
                            Username = "gojo"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Ryomen Sukuna",
                            Password = "sukunapass",
                            Username = "sukuna"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Yuji Itadori",
                            Password = "itadoripass",
                            Username = "itadori"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Nobara Kugisaki",
                            Password = "nobarapass",
                            Username = "nobara"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Aoi Todo",
                            Password = "todopass",
                            Username = "todo"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Toji Fushiguro",
                            Password = "tojipass",
                            Username = "toji"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
