// <auto-generated />
using ConRes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConRes.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260315103950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ConRes.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Aarav Patel",
                            Username = "aarav"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Isha Sharma",
                            Username = "isha"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Dev Kumar",
                            Username = "dev"
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Maya Singh",
                            Username = "maya"
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Rohan Mehta",
                            Username = "rohan"
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "Anika Nair",
                            Username = "anika"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
